language: python
python:
    - "3.6.6"
cache: pip
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - py.test --cov-report term --cov perfsonar_data_helper
#    - py.test --cov-report html:coverage --cov-report term --cov perfsonar_data_helper
    - flake8 perfsonar_data --statistics
